### ISSUE TITLE
question regarding NetworkDecoder.DecodeItemMarketBoardInfo

### ISSUE THREAD

**Issue by zandzpider** [Critical-Impact/CriticalCommonLib#2]
i am using the NetworkDecoder.DecodeItemMarketBoardInfo call to try to get a list of items that my retainer is selling.

the needed fields are name, quality and price

any suggestions? sorry trying to fiddle around with your codebase

**Comment by Critical-Impact** [comment]
The information returned by the network is the slot id, container id and unit price. 
For that information to be of any use you would need to either be parsing ItemInfo network requests or retrieve the market items when you access a retainer. Then once you actually have the items parsed you would need to match the pricing data against the items.

Container ID in both the ItemMarketBoardInfo and ItemInfo network messages refer to a value available in the enum InventoryType.cs (In your case the one you are after is RetainerMarket = 12002)
